[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "sentence-transformers>=6.1.0",
    "streamlit>=1.64.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.1",
]
